export default {
  items: [
    { id: 1, name: "Burger", htmlContent: "<strong>Burger</strong>", textColor: "white", background: "#f2831b" },
    { id: 2, name: "Veggie", htmlContent: "<strong>Veggie</strong>", textColor: "white", background: "#37e307" },
    { id: 3, name: "Pizza", htmlContent: "<strong>Pizza</strong>", textColor: "white", background: "#3ab3f0" },
    { id: 4, name: "Pokebowl", htmlContent: "<strong>Pokebowl</strong>", textColor: "white", background: "#f0403a" },
    { id: 5, name: "Kebab", htmlContent: "<strong>Kebab</strong>", textColor: "white", background: "#f2831b" },
    { id: 6, name: "Salads", htmlContent: "<strong>Salads</strong>", textColor: "white", background: "#37e307" },
    { id: 7, name: "Japanese", htmlContent: "<strong>Japanese</strong>", textColor: "white", background: "#3ab3f0" },
    { id: 8, name: "Pokebowl", htmlContent: "<strong>Pokebowl</strong>", textColor: "white", background: "#f0403a" },
    { id: 9, name: "Thai", htmlContent: "<strong>Burger</strong>", textColor: "white", background: "#f2831b" },
    { id: 10, name: "Sandwich", htmlContent: "<strong>Sandwich</strong>", textColor: "white", background: "#37e307" },
    { id: 11, name: "French", htmlContent: "<strong>French</strong>", textColor: "white", background: "#3ab3f0" },
    { id: 12, name: "Pasta", htmlContent: "<strong>Pasta</strong>", textColor: "white", background: "#f0403a" },
  ],
  firstItemIndex: { value: 0 },
  wheelSettings: {
    centeredIndicator: false,
    indicatorPosition: "right",
    size: 400,
    displayShadow: true,
    duration: 8,
    resultVariation: 70,
    easing: "bounce",
    counterClockwise: false,
    horizontalContent: false,
    displayBorder: true,
    displayIndicator: false,
    baseDisplay: true,
    baseSize: 100,
    baseDisplayShadow: true,
    baseDisplayIndicator: true,
    baseBackground: "#444",
    baseHtmlContent: "<strong class=\"text-white\">What to<br>eat?</strong>",
  }
}